# Generated by Django 2.2.6 on 2019-10-19 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_provider_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
