# Generated by Django 2.2.6 on 2019-10-20 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.Category'),
        ),
    ]
