# Generated by Django 2.2.6 on 2019-10-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_auto_20191020_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
