# Generated by Django 2.2.6 on 2019-10-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0009_provider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
